version: '3'
services:
    web:
        build:
            context: /home/${HOMENAME}/project/deployment/docker/dev/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            # config nginx
            - /home/${HOMENAME}/project/deployment/nginx/symfonyTest.conf:/etc/nginx/conf.d/symfonyTest.conf
            - /home/${HOMENAME}/project/deployment/nginx/symfonyApi.conf:/etc/nginx/conf.d/symfonyApi.conf
            - /home/${HOMENAME}/project/deployment/nginx/vue.conf:/etc/nginx/conf.d/vue.conf
            # передать папки
            - /home/${HOMENAME}/project/symfonyapi:/home/apps/symfonyapi
            - /home/${HOMENAME}/project/symfonyTest:/home/apps/symfonyTest
            - /home/${HOMENAME}/project/vueproject:/home/apps/vueproject
        depends_on:
            - symfonyapi
            - symfonytest
    symfonyapi:
        build:
            context: /home/${HOMENAME}/project/deployment/docker/dev/symfonyapi
            dockerfile: php-fpm.docker
        # должны совпадать с путями из nginx
        volumes:
            - /home/${HOMENAME}/project/symfonyapi:/home/apps/symfonyapi
        depends_on:
            - rabbit
    symfonytest:
        build:
            context: /home/${HOMENAME}/project/deployment/docker/dev/symfonyTest
            dockerfile: php-fpm.docker
        # должны совпадать с путями из nginx
        volumes:
            - /home/${HOMENAME}/project/symfonyTest:/home/apps/symfonyTest
        depends_on:
            - rabbit

         
    postgres:
        build:
            context: /home/${HOMENAME}/project/deployment/docker/dev/postgres
            dockerfile: Dockerfile

        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        ports: 
            - "54321:5432"
        volumes:
            - /home/${HOMENAME}/project/deployment/db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
            - /home/${HOMENAME}/project/deployment/postgres-data:/var/lib/postgresql/data

    
    pgadmin-compose:
        build:
            context: /home/${HOMENAME}/project/deployment/docker/dev/pgadmin
            dockerfile: Dockerfile
        environment: 
            PGADMIN_DEFAULT_EMAIL: "test@mail.ru"
            PGADMIN_DEFAULT_PASSWORD: "test@mail.ru"
        #id = 172.17.0.1
        ports: 
            - "16543:80"
        depends_on: 
            - postgres
    redis:
        build:
            context: /home/${HOMENAME}/project/deployment/docker/dev/redis
            dockerfile: Dockerfile
        ports: 
            - "6379:6379"
    rabbit:
        build:
            context: /home/${HOMENAME}/project/deployment/docker/dev/rabbit
            dockerfile: Dockerfile
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
    vue:
        build:
            context: /home/${HOMENAME}/project/vueproject
            dockerfile: Dockerfile

        ports:
            - "8080:8080"
        volumes:
            - /home/${HOMENAME}/project/vueproject:/home/apps
